[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  DATABASE_URL = "postgresql://neondb_owner:npg_Y1PO0bExMnJZ@ep-solitary-snow-a5nu5zw7-pooler.us-east-2.aws.neon.tech/talentscript?sslmode=require&channel_binding=require"
  NETLIFY_DATABASE_URL = "postgresql://neondb_owner:npg_Y1PO0bExMnJZ@ep-solitary-snow-a5nu5zw7-pooler.us-east-2.aws.neon.tech/talentscript?sslmode=require&channel_binding=require"
  NETLIFY_DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_Y1PO0bExMnJZ@ep-solitary-snow-a5nu5zw7-pooler.us-east-2.aws.neon.tech/talentscript?sslmode=require&channel_binding=require"